services:
  backend:
    build:
      context: backend/.
      args:
        - DATABASE_URL
    container_name: backend
    env_file:
      - .env
    expose:
      - "3002"
#    ports:
#      - "3002:3002" 
    networks:
      - transcendence
    volumes:
      - ./backend/prisma:/app/prisma
  frontend:
    depends_on:
      - backend
    build:
      context: frontend/.
      args:
        - CERT_PATH
        - SSL_CERT_PATH
        - SSL_KEY_PATH
    env_file:
      - .env
    container_name: frontend
    ports:
      - "8443:8443"
    restart: unless-stopped
    networks:
      - transcendence


networks:
  transcendence:
    driver: bridge