services:
  auth-service:
    build: auth-service/.
    container_name: auth-service
    ports:
      - 3002:3002
    networks:
        - meu-network
  frontend-service:
      build:
        context: frontend-service/.
        dockerfile: Dockerfile
      container_name: frontend-service
      ports:
        - "8080:80"
      restart: unless-stopped
      networks:
        - meu-network
      depends_on:
        - api-gateway
  api-gateway:
    build: api-gateway/.
    container_name: api-gateway
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - meu-network
    depends_on:
      - auth-service

networks:
  transcendence:
    driver: bridgey