services:
  backend:
    build: backend/.
    container_name: backend
    expose:
      - "3002"
#    ports:
#      - "3002:3002" 
    networks:
      - transcendence
    volumes:
      - ./backend/prisma:/app/prisma
  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - transcendence


networks:
  transcendence:
    driver: bridge